[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "taif"
version = "0.1.0"
description = "tAIsk force agentic system"
authors = [{name = "nooblife", email = "zackanit@gmail.com"}]
dependencies = [
    "typer",
    "requests",
    "pytest"
] 